- name: Removing Original Git
  yum: name=git state=absent

- name: Installing Git 2 
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=present

- name: Installing Git 2 All
  yum: name=git224-all state=present
